[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glam = "0.24.0"
glutin = "0.30.8"
glutin-winit = "0.3.0"
image = "0.24.6"
raw-window-handle = "0.5.2"
specs = "0.19.0"
tobj = "4.0.0"
winit = "0.28.6"

